### ISSUE TITLE
NullException while creating document -- TextBlock.GetBody

### ISSUE THREAD

**Issue by astrowalker** [egonl/SharpDocx#37]
Thank you very much for this project.

I have problem using it though, because right at the start, when you are loading/creating the document with `DocumentFactory.Create` I got null exception. The issue is with `TextBlock.GetBody` and its loop `while (nextElement != endParent)`.

Inside the body there is soft casting to `OpenXmlCompositeElement` on the assumption that every element is indeed `OpenXmlCompositeElement`, but if it is not the case, the outcome of the cast would be null, and on next iteration null exception will be thrown.

And in my case it is what happens, at one point `DocumentFormat.OpenXml.Wordprocessing.BookmarkEnd` appears (it does not inherit from `OpenXmlCompositeElement`).

**Comment by egonl** [comment]
Fixed it in version 2.2.0. Could you give it a try?

**Comment by astrowalker** [comment]
Thank you, I tested it, I don't see this error, but `DocumentFactory.Create` call still cannot succesfully finish. I get "SharpDocx.SharpDocxCompilationException" exception and in formattedErrors I see such content:

```
{    1  using System;
    2  using DocumentFormat.OpenXml.Wordprocessing;
    3  using SharpDocx.CodeBlocks;
    4  using SharpDocx.Models;
    5  
    6  
    7  namespace SharpDocx
    8  {
    9      public class SharpDocument_312b131393d343b68ffbb4e206eeaf2a : DocumentBase
   10      {
   11          public string Model { get; set; }
   12  
   13          protected override void InvokeDocumentCode()
   14          {
   15              CurrentTextBlockStack.Push(CurrentTextBlock);
   16              CurrentTextBlock = CodeBlocks[0] as TextBlock;
   17              CurrentCodeBlock = CodeBlocks[0];
   18              foreach (var sensor in Model.Sensors) { 
   19              CurrentCodeBlock = CodeBlocks[1];
   20              Write( sensor.Name );
   21              CurrentCodeBlock = CodeBlocks[2];
   22              Write( sensor.Summary );
   23              AppendTextBlock();
   24              CurrentCodeBlock = CodeBlocks[3];
   25              } 
   26              CurrentTextBlock = CurrentTextBlockStack.Pop();
   27  
   28          }
   29  
   30          public override void SetModel(object model)
   31          {
   32              if (model == null)
   33              {
   34                  Model = null;
   35                  return;
   36              }
   37  
   38              Model = model as string;
   39  
   40              if (Model == null)
   41              {
   42                  throw new ArgumentException("Model is not of type string", "model");
   43              }
   44          }
   45      }
   46  }
}```

**Comment by egonl** [comment]
Could you post the view here as an attachment, so I can reproduce it?

**Comment by egonl** [comment]
Could you also post how you're calling SharpDocx? I guess you're doing something like:
```
            var document = DocumentFactory.Create(viewPath);
```
instead of
```
            var document = DocumentFactory.Create(viewPath, model);
```
DocumentFactory needs to know the type of the model. If it doesn't, it will generate `public string Model { get; set; }` instead of `public MyViewModelType Model { get; set; }`.

**Comment by astrowalker** [comment]
Many thanks for the update. Indeed I have such combo
```
Create...
SetModel
```

and the first one failed. Now I have `Create` with two arguments as you shown, and the creation was successful. So I think it is safe to close this report as fixed. Once again, thank you very much!
